# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aa50abb59c5cc73166aa68df0220562e6c3650b5edf0e83a60cd9c42510d616135d5cafa17b8beb3ef91c9bd1f437ae5da377d14e5deac5249428a914dd12f1

test:
  secret_key_base: becc698a6cf4e7ae4015e6f7e82788600da6e2f180fe5ed793bb875476befded07f831cfcef83bc249ea5da18cf6689e8d6eba70d8b8520037c26b56443eee36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
